"""Added chat_logs and handoff models

Revision ID: 461c4ed19bc7
Revises: 262cb310b253
Create Date: 2025-11-29 15:40:22.984302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '461c4ed19bc7'
down_revision: Union[str, None] = '262cb310b253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_client_id'), 'chat_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_timestamp'), 'chat_logs', ['timestamp'], unique=False)
    op.create_table('handoff_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='handoffstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handoff_tickets_client_id'), 'handoff_tickets', ['client_id'], unique=False)
    op.create_index(op.f('ix_handoff_tickets_created_at'), 'handoff_tickets', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handoff_tickets_created_at'), table_name='handoff_tickets')
    op.drop_index(op.f('ix_handoff_tickets_client_id'), table_name='handoff_tickets')
    op.drop_table('handoff_tickets')
    op.drop_index(op.f('ix_chat_logs_timestamp'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_client_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    # ### end Alembic commands ###
